"""migration 2

Revision ID: 98eaab43507d
Revises: 939996e1c24a
Create Date: 2026-06-02 23:47:21.572072

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98eaab43507d'
down_revision: Union[str, Sequence[str], None] = '939996e1c24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
